version: "3.8"

services:
  pg_tks:
    build: .
    image: tks_pg_custom
    container_name: pg_tks
    hostname: pg_tks
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rentdb
      POSTGRES_USER: rent
      POSTGRES_PASSWORD: rent
    volumes:
      - rent:/var/lib/postgresql/data

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
volumes:
  rent: